name: CI

on:
  push:
    branches:
      - master
      - github-actions
  pull_request:
    branches:
      - master
      - github-actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x test.sh

      - name: Run simple tests
        run: ./test.sh

  docker:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        actions: read
      needs: test
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Build Docker image
          run: docker build -t my-app .
          
        - name: Log in to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN }}
            
        - name: Push to GHCR
          run: |
            docker tag my-app ghcr.io/darktezi/static-website-example:latest
            docker push ghcr.io/darktezi/static-website-example:latest